### ISSUE TITLE
new MS figures for 2020-05-06

### ISSUE THREAD

**Issue by bfeldman89** [themarshallproject/COVID_prison_data#3]
"Reeves said Wednesday that **37** Mississippi inmates have been tested for the virus, and **four** of those tested positive. He said **43** Department of Corrections staff members have been tested, and **seven** of those tested positive." https://www.wtva.com/content/state/Mississippi-gov-says-pandemic-no-excuse-to-release-inmates-570262271.html

**Comment by bfeldman89** [comment]
Actually, as of 2020-05-07, there are five confirmed cases in MS prisons. However, the other three data points are unknown. 

[![Screen Shot 2020-05-07 at 11 22 18 AM](https://user-images.githubusercontent.com/26087892/81319310-1bb9c200-9055-11ea-9f5d-9c16aa8c86eb.png)](https://www.mdoc.ms.gov/Documents/Inmates%20positive%20test%20chart%20(3).pdf)

**Comment by tommeagher** [comment]
Thanks, Blake! Appreciate the heads up.
