### ISSUE TITLE
Bad date in covid_prison_cases.csv

### ISSUE THREAD

**Issue by Dulani** [themarshallproject/COVID_prison_data#4]
Hey Marshall Project, thanks for this public service!  I believe there is an error in the date on line 398 of `covid_prison_cases.csv` which is for South Carolina.  The date says: `06/29/2020` and it looks like it should be `09/29/2020` (based on the actual numbers and its order in the file).

**Comment by tommeagher** [comment]
@Dulani Thank you for flagging this. You are correct, that should be `09/29/20`. We will correct this with our next data release, which should be Thursday, Dec. 3. Thanks again!
