### ISSUE TITLE
Wrong year in a few dates 

### ISSUE THREAD

**Issue by erika-tyagi** [themarshallproject/COVID_prison_data#5]
Hi! I think there might be a few dates with the wrong year specified (2020 instead of 2021) in `covid_prison_cases.csv`: 
* Alabama: 04/21/2020 and 04/07/2020
* Arizona: 04/06/2020
* Missouri: 04/06/2020
* Washington: 03/23/2020

Thank you as always for your work collecting and sharing this data!

**Comment by tommeagher** [comment]
@erika-tyagi Thank you for flagging these for us!  I have no idea what happened that week of 4/6, but you are right. We will correct these in our next data release, which should be on Friday, May 13. Thanks!
